### ISSUE TITLE
Spacing on the text below

### ISSUE THREAD

**Issue by BryanCJW** [joleaf/obsidian-email-block-plugin#10]
Thanks Joleaf for the previous answer, also needed to ask how do I make spacing for the text below as I tried to space after an email text but it could not be shown.

Example: 

**Event**
Hi (name), how are you, Best Regards

**Expected**
Hi (name), 

How are you 

Best Regards,

**Comment by BryanCJW** [comment]
Hello so is this doable?

**Comment by joleaf** [comment]
The Mail To API does not support HTML tags, just simple "newline" characters. Unfortunately, only one line is then rendered.
A future version may be based on a library that supports multiple new lines.
