### ISSUE TITLE
prompt for fields instead of template

### ISSUE THREAD

**Issue by pcause** [joleaf/obsidian-email-block-plugin#11]
Lots of folks want to send email from obsidian and I've used your plugin and it has helped me.  I was wondering about adding a command to send note as email which would prompt in a modal for the various email fields (to,cc,bcc, subject) and use the current note (or perhaps selection as a second option) and send that as the email.  Makes it easier to use that having to think about creating a template and adding it to a note.

**Comment by joleaf** [comment]
Think this is not the key purpose of this plugin.
