### ISSUE TITLE
Allow field to use variables

### ISSUE THREAD

**Issue by VSuryaPrashanth** [joleaf/obsidian-email-block-plugin#12]
I like to have all my variables in the font-matter, so I can structure it batter.
i.e.
```
---
email:
  from: some@mail.com
  to: some@mail.com
  subject: some thing
  body: |
    Multi
    Line
    Some
    thing
---
```
Since we can already access the font-matter variable in the body, I think it will be good to do the same in other fields as well.
i.e.
````
```email
to: info@randommail.com
subject: My Subject
cc: {{myvar}}
body: [[MyMail4711]]
variables:
  myvar: TestVar
```
````

**Comment by Vrum89** [comment]
I'd like to have it!
Especially for the subject.

It could be a game-changer for me :)

**Comment by Vrum89** [comment]
Hi,

I should have done it in my pull request (https://github.com/joleaf/obsidian-email-block-plugin/pull/15)
I'm waiting for approval. 
Let me see If you can run it properly. The feature work on the subject only.

Example (with property 'name')

````
```email
to: info@randommail.com
subject: reminder for {{name}}
---
Dear {{name}},
this is not a personal email.
Regards,
FI
```
````
![image](https://github.com/joleaf/obsidian-email-block-plugin/assets/39809579/f295bf96-8489-473a-b604-0e7e842e1439)





Francesco

**Comment by joleaf** [comment]
Have fun :)
