### ISSUE TITLE
Email parameters invalid

### ISSUE THREAD

**Issue by helicos6** [joleaf/obsidian-email-block-plugin#14]
Hi,

I just downloaded this plugin to try and can't seem to make it work.

I tried this example:

````
```email
to: info@randommail.com
subject: My Subject
body: "Hey info,

  here is some content"
```
````

I am getting this error:

Email parameters invalid: Cannot read properties of null (reading 'toString')

<img width="600" alt="43264" src="https://github.com/joleaf/obsidian-email-block-plugin/assets/34452093/4d6fa9f9-a37c-42ea-adea-2a4d3216e4d0">

Any idea what the issue could be?

Thanks!

**Comment by joleaf** [comment]
This example works in my test environment. Can you please check, if another plugin influences this plugin?

**Comment by xxie-xd** [comment]
It seems that markdown file with a YAML frontmatter entry which doesn't have an `toString()` method will cause this error.
[Test.md](https://github.com/user-attachments/files/15883008/Test.md)
