### ISSUE TITLE
add a "&bcc=" in the cc block

### ISSUE THREAD

**Issue by pcause** [joleaf/obsidian-email-block-plugin#2]
First, great addin and thnaks.  I use the example you gie and am on Win11.  I have the sendto link enabled.  When I click the nessage fields included (to, subject, body) are all filled in with what I have in the block.  However, the cc field that Outlook (desktop) displays is filled in with "&bcc=" even though I have no cc or bcc field.

I would assume that if the field is missing or empty, you'd leave out the &bcc or &cc from then URL to invoke the email client.

**Comment by joleaf** [comment]
@pcause Should be fixed. Can you please confirm this? Thank you!

**Comment by pcause** [comment]
did a quick check with same block and no bcc on the cc line.  thanks
