### ISSUE TITLE
0.4.0 blank header data causes error

### ISSUE THREAD

**Issue by pcause** [joleaf/obsidian-email-block-plugin#5]
Thanks fir the new format.  Works really well.  There is one issue.  I created a quickadd function.  It inserts this into a note:

````
```email
to: 
cc: 
bcc: 
subject: 
---
```
````

if I just fill in the to/subject and message but leave cc and bcc empty I get an error about parsing and null

**Comment by joleaf** [comment]
Hey @pcause. Yes, this behaviour is correct. The yaml parser expects a value for a given key.
I don't know quickadd, but maybe you can set the default to   ""    ? Then, yaml sees a blank string.
