### ISSUE TITLE
Error "Email parameters invalud: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by BrianJChoi** [joleaf/obsidian-email-block-plugin#6]
Hi joleaf!

I have followed the Readme page, but the email block doesn't seem to work properly getting this error
"Error "Email parameters invalud: Cannot read properties of null (reading 'toString')"

To try it out I made a sample code block as follows.
Is there something wrong?
````
```email
to: jiwoongchoi@outlook.com
subject: Hello
---
Example
```
````

**Comment by joleaf** [comment]
Hey @BrianJChoi , what is the plugin version you use?

**Comment by BrianJChoi** [comment]
Thanks for the prompt reply!
I am using the latest version (as I am aware of), version 0.4.0 as I installed from the Obsidian Community Plugin Store directly!

**Comment by joleaf** [comment]
Mh, the example works in my obsidian :D Can you post a screenshot from the plain source code and then from the error message?

**Comment by BrianJChoi** [comment]
Uploaded a short video! (2x sped up)
It seems to work on new note pages, but not on ones that are already present.. hmm
I will have to try some things out fror mysefl, but thanks!

https://www.youtube.com/watch?v=pwVyOYx6n8M

**Comment by joleaf** [comment]
mh, maybe the metadata of the current note? Can you remove this and test it again?
