### ISSUE TITLE
Recognize from field

### ISSUE THREAD

**Issue by matclab** [joleaf/obsidian-email-block-plugin#8]
It would be nice to allow and format a `from:` field.
I use it to nicely show mails received when I want to keep them in my notes.

**Comment by joleaf** [comment]
Hey @matclab,
Thank you for your suggestion. So, do you want this field `from` just for "Documenting" your email? 
The mailto API does not support a `from` field (See [here](https://stackoverflow.com/questions/9380924/is-it-possible-to-modify-from-field-in-mailto-link)), and that means that this field can only be used for the preview, but not for the `Mailto` button. Is this your intention?

**Comment by matclab** [comment]
Yes, totally, just for documenting.

**Comment by joleaf** [comment]
@matclab have fun ;)

**Comment by matclab** [comment]
Thank you very much @joleaf :clap:
